"""init

Revision ID: 1a1de1a4f4aa
Revises: 
Create Date: 2026-07-26 14:43:42.931311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1de1a4f4aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('material_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('core_size_nm', sa.Float(), nullable=True),
    sa.Column('zeta_potential_mv', sa.Float(), nullable=True),
    sa.Column('surface_area_m2g', sa.Float(), nullable=True),
    sa.Column('coating', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_performance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nanomaterial', sa.String(), nullable=False),
    sa.Column('analyte', sa.String(), nullable=False),
    sa.Column('lod_mol_per_l', sa.Float(), nullable=True),
    sa.Column('sensitivity_value', sa.Float(), nullable=True),
    sa.Column('sensitivity_unit', sa.String(), nullable=True),
    sa.Column('linear_range_low', sa.Float(), nullable=True),
    sa.Column('linear_range_high', sa.Float(), nullable=True),
    sa.Column('response_time_s', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toxicity_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('ic50', sa.Float(), nullable=True),
    sa.Column('ec50', sa.Float(), nullable=True),
    sa.Column('pec50', sa.Float(), nullable=True),
    sa.Column('cell_line', sa.String(), nullable=True),
    sa.Column('exposure_time_h', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toxicity_records')
    op.drop_table('sensor_performance_records')
    op.drop_table('record_versions')
    op.drop_table('record_reviews')
    op.drop_table('material_records')
    op.drop_table('users')
    # ### end Alembic commands ###
