"""remove_toxicity_classification_column

Revision ID: 40200d40ce1e
Revises: 6adb806bf23f
Create Date: 2026-08-04 19:06:12.604631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40200d40ce1e'
down_revision: Union[str, Sequence[str], None] = '6adb806bf23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
