"""remove_toxicity_classification_trinh_only

Revision ID: 866dfd33dde4
Revises: cfb7cd2455b1
Create Date: 2026-07-27 09:09:21.954551

Removes the toxicity_classification column from toxicity_records.

Rationale: This column was added exclusively for the Trinh mixture toxicity dataset
(migration cfb7cd2455b1). However, the Trinh dataset is a literature-review metadata
catalog (citations, study methodology, test organisms) — it contains NO actual
toxicity outcome values (no IC50/EC50 measured values, no material property data).
It should not have been ingested as ToxicityRecord data.

All 40 Trinh-sourced ToxicityRecord and MaterialRecord rows have been deleted from
the database. No other ingestion script (cananolab, nanopharos, zenodo_toxicity) uses
or references toxicity_classification. The column had 0 non-NULL rows at time of removal.

The Trinh dataset is retained as data/processed/trinh_clean.csv for reference only.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866dfd33dde4'
down_revision: Union[str, Sequence[str], None] = 'cfb7cd2455b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toxicity_records', 'toxicity_classification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toxicity_records', sa.Column('toxicity_classification', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
