"""add_aie_cnes_records_table

Revision ID: add_aie_cnes_records
Revises: 6adb806bf23f
Create Date: 2026-08-16

Adds aie_cnes_records — a fully isolated table for the AIE_CNES_Dataset.csv
(7,654 rows, graphene/CNT sensor data).

This table is INTENTIONALLY SEPARATE from sensor_performance_records.
The dataset shows structural indicators of possible synthetic origin:
perfect data quality (0 missing values), tightly bounded numeric ranges,
and binary classification labels. No source paper or laboratory provenance provided.

Every row carries an immutable provenance_note field stating:
  "Provenance unverified. No cited source paper or laboratory. Structural indicators
   suggest possible synthetic origin: perfect data quality (0 missing values),
   tightly bounded numeric ranges, binary classification labels. Use only as
   plausibility-range reference, not as literature-grade or experimentally validated data."
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_aie_cnes_records'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aie_cnes_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graphene_ratio_pct', sa.Float(), nullable=True),
    sa.Column('cnt_ratio_pct', sa.Float(), nullable=True),
    sa.Column('electrode_surface_area_cm2', sa.Float(), nullable=True),
    sa.Column('conductivity_s_m', sa.Float(), nullable=True),
    sa.Column('ph_level', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('potential_v', sa.Float(), nullable=True),
    sa.Column('current_ua', sa.Float(), nullable=True),
    sa.Column('scan_rate_mv_s', sa.Float(), nullable=True),
    sa.Column('pulse_amplitude_mv', sa.Float(), nullable=True),
    sa.Column('peak_current_ua', sa.Float(), nullable=True),
    sa.Column('peak_potential_v', sa.Float(), nullable=True),
    sa.Column('snr', sa.Float(), nullable=True),
    sa.Column('interference_level_pct', sa.Float(), nullable=True),
    sa.Column('pollutant_type', sa.String(), nullable=True),
    sa.Column('pollutant_concentration_ppm', sa.Float(), nullable=True),
    sa.Column('detection_status', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('provenance_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aie_cnes_records')
    # ### end Alembic commands ###
