"""add_analyte_compounds_table

Revision ID: add_analyte_compounds
Revises: add_aie_cnes_records
Create Date: 2026-08-16

Adds analyte_compounds table for molecular reference properties of analytes.
Stores PubChem data for common analytes (arsenic, cadmium, dopamine, glucose, lead, mercury, nitrate, cotisol)
that can be matched against in Design Studio searches.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_analyte_compounds'
down_revision: Union[str, Sequence[str], None] = 'add_aie_cnes_records'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyte_compounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pubchem_cid', sa.Integer(), nullable=True),
    sa.Column('molecular_formula', sa.String(), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.Column('xlogp', sa.Float(), nullable=True),
    sa.Column('tpsa', sa.Float(), nullable=True),
    sa.Column('hbond_donor_count', sa.Integer(), nullable=True),
    sa.Column('hbond_acceptor_count', sa.Integer(), nullable=True),
    sa.Column('complexity', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyte_compounds')
    # ### end Alembic commands ###
