"""add_toxicity_classification_column

Revision ID: cfb7cd2455b1
Revises: 1a1de1a4f4aa
Create Date: 2026-07-27 08:42:08.408733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb7cd2455b1'
down_revision: Union[str, Sequence[str], None] = '1a1de1a4f4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toxicity_records', sa.Column('toxicity_classification', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toxicity_records', 'toxicity_classification')
    # ### end Alembic commands ###
